#! /bin/sh

#remove rules
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &


###---Monitors---###
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 


##---Global Settings---###
bspc config border_width        4
bspc config window_gap          14
bspc config top_padding		0
bspc config bottom_padding	26

bspc config split_ratio          0.54

bspc config borderless_monocle   true
bspc config gapless_monocle      true

#color theming
bspc config focused_border_color "#32c5fe" 

#start polybar
killall -q polybar
echo "---" | tee -a /tmp/polybar1.log
polybar main 2>&1 | tee -a /tmp/polybar1.log & disown
